---
- hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: download the docker convenience script for ubuntu
      get_url:
        url: https://get.docker.com
        dest: /home/ubuntu/get-docker.sh
        mode: '0755'

    - name: run the convenience script
      shell: /home/ubuntu/get-docker.sh

    - name: add user "ubuntu" to docker
      command: usermod -aG docker ubuntu

    - name : download the current stable release of docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'


